# Generated by Django 5.2.7 on 2025-12-28 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laporanharian',
            name='user',
        ),
    ]
